### ISSUE TITLE
ARMv8-M MPU setup appears to have an off-by-32 error

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#1016]
@flihp has been having a hard time making abutting regions on the LPC55; reviewing the kernel code I noticed this:

```rust
        let rlar = (region.base + region.size)
                | (i as u32) << 1 // AttrIndx
                | (1 << 0); // enable
```

The RLAR LIMIT field is described by ARM as containing...

> Ending address (upper inclusive limit)of MPU region address (bits [31:5] - the address must be aligned to multiple of 32 bytes). Bit [4:0] of the address value is assigned with 0x1F to provide the limit address to be checked against.

This means I think we've got an off-by-1-32-byte-chunk error on all regions right now, that needs to have a `- 32` added.

**Comment by flihp** [comment]
Thanks for the explanation! PR is up: #1017
