### ISSUE TITLE
Audit RAM usage against IAP requirements

### ISSUE THREAD

**Issue by labbott** [oxidecomputer/hubris#1051]
Section 8.3.4.2 of the LPC55 manual gives the following:

```
Below regions are reserved for bootloader use when the bootloader is running. The heap
and the BSS, RW section need to be reserved for the ROM API use before calling the
ROM APIs in user application (IAP scenario).
```
![reserved_ram](https://user-images.githubusercontent.com/5463647/210638418-d46a9f97-d332-473a-9055-937994ab9bcf.png)

We aren't currently using the BSS sections (SRAMX memory) and unless we're going to call the secure boot functions we shouldn't be doing anything with the heap. It would still be good to double check that our ROM API usage isn't going to give us any surprises. (Or we finally bite the bullet and stop using the ROM APIs. That is always a valid choice to consider)

**Comment by cbiffle** [comment]
This should be fixed now:
- bootleby uses the ROM APIs but reserves the required memory in its linker script
- Hubris both reserves the memory, _and_ has stopped using the ROM APIs. Just, y'know, to be extra safe I guess? :-)
