### ISSUE TITLE
Move hypocalls (aka TrustZone) back into stage0

### ISSUE THREAD

**Issue by labbott** [oxidecomputer/hubris#1062]
We currently ship our TrustZone callable interface referred to as 'hypovisor' with Hubris. Practically, this works well but it creates an unfortunate trust inversion: stage0 is supposed to be more trusted than Hubris which means updating stage0 relies on trusting the hypocalls. The choice to ship the hypocalls with Hubris was the result of two major problems:

1) Calling into TrustZone requires knowing the absolute addresses of the TrustZone non-secure callable entry points. Previous attempts at building this with stage0 were a pain.
2) We need the update code to not get erased while attempting to do an update. There isn't space to have dual copies.

Suggested approach for moving back to stage0:
- Locate the update code in SRAM. This solves the issue of the update code being erased out from under us.
-- Collecting all the update code to put in a single section turns out to be annoying. It's easy to mark a single data structure or a single asm function as being part of a specific section but much more difficult to collect an entire Rust function. From experience, the easiest way to do this is to build all wanted code as a dedicated executable. This is the approach we take with the fake `secure` task and I suggest porting the same approach over to stage0: build our update code as an executable linked at whatever address we want it to run at, append that binary to the end(?) of stage0, have stage0 relocate that code before it jumps to Hubris.
- Keep using the dedicated `tz_table` interfaces for telling Hubris where the TZ NSC entry points live. This abstraction works reasonablly well and it's easy to update it operating on a `stage0` binary instead of a `secure` task. The table of `nsc` entry points will still need to be collected and live somewhere (also in SRAM?)
-  The SAU entries currently live in the Hubris header which also creates a trust inversion. That information should all be moved back to stage0 as well.

This should all be taken as notes on _a_ possible approach. The actual requirement is "fix the trust inversion for updating stage0"

**Comment by cbiffle** [comment]
This problem has changed slightly with the RFD374/bootleby transition, but is still valid; merging into #1318 .
