### ISSUE TITLE
RoT on Gimlet needs to respect the `GND_DETECT` line on the SP JTAG header

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#1073]
The RoT on Gimlet has control over the SP's SWD port; this port is also routed to a header for use with an external programming dongle.

We ran a net to the RoT to detect presence of such a dongle, so that it can release the SWD pins to make sure that (1) the two drivers are not fighting and (2) SWD actually works. Currently the RoT is not respecting this line.

It probably should!

It looks like (@nathanaelhuffman to confirm) the board has resistors on the right nets to keep the drivers from destroying each other, so this is probably not a hardware damage issue.

@bcantrill @kc8apf

**Comment by nathanaelhuffman** [comment]
Currently I'm concerned about the implementation on our current-gen boards.
![image](https://user-images.githubusercontent.com/8078693/211420310-cb0788ea-0ba7-4717-905a-29bde30891e4.png)

I've opened issues to increase the series resistance on all the lines for the PVT spin, but above is the implementation on all our current hardware in-hand.

sidecar: https://github.com/oxidecomputer/hardware-sidecar/issues/755
gimlet: https://github.com/oxidecomputer/hardware-gimlet#1864
psc: https://github.com/oxidecomputer/hardware-psc/issues/317

**Comment by isobering** [comment]
@cbiffle - for someone who wasn't involved in the original discussion, which ROT net is supposed to be detecting the presence of an SP dongle? Based on the net names alone, someone reading the Gimlet schematic would infer that both `ROT_TO_SP_SWDIO_MOSI_R` and `ROT_TO_SP_SWDIO_MISO_R` are intended to operate as data IO pins.

**Comment by nathanaelhuffman** [comment]
@isobering I can help here (these shots from gimlet, but the other boards should have similar circuits):

RoT pin for SP jtag detection:
![image](https://user-images.githubusercontent.com/8078693/211610720-9955c9f1-6e64-47a8-a01c-54628f8b3e58.png)

St-link or equiv dongle pulls that pin down when connected:
![image](https://user-images.githubusercontent.com/8078693/211610794-17a0774f-2cb3-446f-a9b1-29469a0f1e09.png)

Note that the change we're making in hw is beefing up the series resistors to 300 Ohm such that if this detect fails we don't accidentally dead-short pins between RoT and dongle.
