### ISSUE TITLE
Size mismatch in FromPrimitive in Idol file may go unnoticed

### ISSUE THREAD

**Issue by arjenroodselaar** [oxidecomputer/hubris#1138]
Given the following enum..
```
#[derive(Copy, Clone, PartialEq, Eq, FromPrimitive, AsBytes)]
#[repr(u32)]
pub enum DirectBarSegment {
    Bar0 = 0,
    Msi = 1 << 28,
    Cfg = 2 << 28,
}
```
.. and the following snippet from an Idol file..
```
"tofino_read_direct": (
    doc: "Direct read a Tofino register in the given segment",
    args: {
        "segment": (
            type: "DirectBarSegment",
            recv: FromPrimitive("u8"),
        ),
        "offset": "u32",
    },
    reply: Result(
        ok: "u32",
        err: CLike("SeqError"),
    ),
),
```
.. and the implementation of the server side method..
```
    fn tofino_read_direct(
        &mut self,
        _: &RecvMessage,
        segment: DirectBarSegment,
        offset: u32,
    ) -> Result<u32, RequestError<SeqError>> { ... }
```

.. I somewhat naively expect an error/warning from the compiler about `DirectBarSegment` being the wrong size. But this compiles and does not cause a problem until Humility tries to pass a 1 byte value to Hiffy. Is this something we can catch earlier?

**Comment by cbiffle** [comment]
I recommend using `encoding: Hubpack` which doesn't need the conversions and should just work, assuming your enums have 256 variants or fewer. I'm hoping to move things off of the original legacy encoding and deprecate it at some point.
