### ISSUE TITLE
host-sp-comms should commandeer flash for hf

### ISSUE THREAD

**Issue by wesolows** [oxidecomputer/hubris#1172]
On Gimlet, upon receipt of the first IPCC message of any kind from the host, regardless of the nature or disposition of that message, ownership of the boot flash storage should be returned to the SP.  Subsequent access from the host should not be permitted until a transition through A2.

**Comment by cbiffle** [comment]
It's worth noting that, on the _other side_ of the algorithm deciding when to give flash to SP, @wesolows has noted:

> It's not sufficient to give the host the flash when entering A0.  It must be done before leaving A2 on the way to A1.
