### ISSUE TITLE
Need Sidecar Rev C app.toml

### ISSUE THREAD

**Issue by rmustacc** [oxidecomputer/hubris#1211]
We need to go through and add support for Rev C Sidecar's as there have been likely been SP visible electrical changes here. This ticket will be updated to include known issues, but we will need to do a scan regardless.

This also needs to be added to CI.

**Comment by arjenroodselaar** [comment]
Issued tagged from the `hardware-sidecar` and `quartz` repos:

- [ ] https://github.com/oxidecomputer/hardware-sidecar/issues/725
- [ ] https://github.com/oxidecomputer/hardware-sidecar/issues/747, but these signals may have never been implemented in the SP so this may only touch the mainboard controller bitstream
- [ ] https://github.com/oxidecomputer/quartz/issues/83

**Comment by arjenroodselaar** [comment]
With #1231 landing rev C support is now available in the usual places.
