### ISSUE TITLE
Dumping needs to go through something other than udprpc

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#1217]
We will probably want remote dumping in prod. We do not want udprpc in prod. So, we need to route dumping through some other facility -- either a network socket on the dump agent itself (which means it'd work even when e.g. control-plane-agent is hung up), or maybe control-plane-agent.

**Comment by jclulow** [comment]
I feel like many of the dumps I have personally needed to take thus far have been when CPA has become unresponsive, so I would probably vote for isolation if possible.

**Comment by cbiffle** [comment]
I believe this is effectively fixed after @mkeeter's work on dump-agent.
