### ISSUE TITLE
update over management network should interlock against image for incorrect board

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/hubris#1223]
We're expecting a mixed population of system board revisions in test environments shortly, and there is currently (to my knowledge) no protection against using the update server over the management network to install software for board revision A into a board of revision B.  The results of such an operation are presumably, at minimum, a trip to the bench for external reprogramming; and at worst, some physically destructive event that would require board rework to revive the system.

@jgallagher suggests we could put an interlock into the update server task (or possibly the control plane agent) which checks the caboose of the incoming image and rejects it if it is not right for this board.

See also the internal lab ticket about this: oxidecomputer/meta#140.

**Comment by mkeeter** [comment]
Done in #1232
