### ISSUE TITLE
Plumb SP Bank Version information to MGS

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/hubris#1286]
The control plane/mupdate will need to know which software version is installed on each bank of the SP. We will use this so that we can control boot selection and match versions for redundancy once a version has been deemed "good".

**Comment by andrewjstone** [comment]
Assigned to @mkeeter as he is working on getting this information from the caboose to MGS this afternoon.

**Comment by jgallagher** [comment]
I believe this is done as of https://github.com/oxidecomputer/management-gateway-service/pull/91 and https://github.com/oxidecomputer/omicron/pull/3239.
