### ISSUE TITLE
smoltcp sockets can clog if a peer becomes unaddressable

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#1317]
This is our tracking counterpart to upstream https://github.com/smoltcp-rs/smoltcp/issues/594 .

The scope of effort on our side is to make our software robust against this bug until it can be fixed upstream. The intent is that, while we may lose some packet state when we need to take action to clear the socket-clogged condition, we will not unrecoverably drop off the network like we did originally -- and ideally we'll lose as little packet state as reasonably possible.

**Comment by mkeeter** [comment]
Local workarounds exist in #1311 and #1293; we haven't seen the problem since.
