### ISSUE TITLE
Expose the entire CFPA as a blob

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/hubris#1355]
This needs to be added to sprot and plumbed up through MGS.

Ideally, this will be transmitted over an attested channel. That channel may not be ready by the time we want to expose this information.

**Comment by labbott** [comment]
Can you give a few more details why this is needed?

**Comment by andrewjstone** [comment]
I'm not sure it's strictly needed. IIRC we were contemplating this for debugging purposes, given none of the CFPA data is confidential.

**Comment by labbott** [comment]
See #1525 which is adding this

**Comment by labbott** [comment]
We added this in #1525 as well as exposing the CMPA. This was necessary to determine which image to load on a particular system.
