### ISSUE TITLE
Include Gimlet D M.2 drives in `validate` output.

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#1387]
In #888 we made some changes to support the Gimlet B-C I2C mux issue, wherein attempting to talk to the M.2 disks when they're not powered would permanently take out the I2C bus (by muxing a black hole).

@Aaron-Hartwig would like this reversed for D rev so that we can validate the M.2s. I've attempted to do it based on the diff in #888 but can't get it to work, so I think some other things have changed since. Halp.

**Comment by cbiffle** [comment]
Tagging @bcantrill because @mkeeter's on vacation.

**Comment by mkeeter** [comment]
Should we open a PR for that branch?  It looks reasonable to me!
