### ISSUE TITLE
Persistent identitiy keypair potentially left in RAM after use

### ISSUE THREAD

**Issue by mx-shift** [oxidecomputer/hubris#1405]
`run()` in lib/lpc55-rot-startup/src/dice.rs calls `gen_mfg_artifacts()` which returns a `MfgResult` which includes a `salty::KeyPair` containing the public and private platform identity keys.  This is used by `gen_deviceid_artifacts()` to create a certificate chain.  Neither `MfgResult` nor `KeyPair` implement `ZeroizeOnDrop` so when `run()` returns, the private key may still be held in RAM.

**Comment by cbiffle** [comment]
We addressed this by (1) auditing the RAM areas the code uses for zeroization, and then (2) nuking the entire stack on exit from the routine to eliminate anything we missed.
