### ISSUE TITLE
`HostPanic` and `HostBootFailure` discard bytes

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/hubris#1554]
We noticed that `LAST_HOST_PANIC` has silently trimmed two bytes from the data array (based on the point where the ASCII panic string starts).  This appears to be a mistake in `HostToSp::HostPanic`, which consumes a `code: u16`.

There is no leading `u16`; this eats `ipd_version` and one byte of `ipd_cause` (https://github.com/oxidecomputer/illumos-gate/blob/24d1bae12beef37addeb22401ae8d98d302f4021/usr/src/uts/oxide/sys/kernel_ipcc.h#L72-L73).  We should probably just remove the `u16` entirely and store the whole blob.

(the same is true for `HostToSp::HostBootFailure`)

**Comment by bcantrill** [comment]
Note that `HostBootFailure` is correctly interpreted, but we are discarding the `reason`. Fixing this to fix `HostPanic` (which Humility already works around, but should be fixed regardless) and to retain the `reason` on a `HostBootFailure`.
