### ISSUE TITLE
query vpd lock status from `pilot racktest`

### ISSUE THREAD

**Issue by flihp** [oxidecomputer/hubris#1604]
This comes from a https://github.com/oxidecomputer/facade/issues/115. Hubris exposes this currently via the `vpd` task & IDL. This allows `facade` to do the programming and locking. The mfg process definition however defines the `pilot racktest` as that gate that a platform must pass before being shipped. So once the debug probes are removed we need a mechanism to query the lock bit on the VPDs (which & where?)

**Comment by labbott** [comment]
The hubris side of this is now merged, closing
