### ISSUE TITLE
gimlet: capture sequencer T6 state on power off

### ISSUE THREAD

**Issue by rmustacc** [oxidecomputer/hubris#1648]
There are several occasions when the T6 fails to come up successfully and therefore is powered off. When this happens it'd be helpful if the sequencer task captured and at the minimum right now tossed in the ringbuf as data for the power off transition prior to issuing the command to the sequencer. I think the registers we want are:

* `IFR`
* `NIC_CTRL`
* `NIC_STATUS`
* `OUT_STATUS_NIC1`
* `OUT_STATUS_NIC2`
* `AMD_STATUS`

I believe these'll help us understand where this is going on and how it fails.

**Comment by hawkw** [comment]
@rmustacc I've opened PR #1649 to record the registers we don't currently capture. Let me know what you think of this change?
