### ISSUE TITLE
indifferent trace semantics in wiggle_scl

### ISSUE THREAD

**Issue by rosenkiesel** [oxidecomputer/hubris#1744]
This is too subtle:

https://github.com/oxidecomputer/hubris/blob/abfdfbe4edbbb95d1cbf11c14074e91bccfb0820/drv/stm32xx-i2c-server/src/main.rs#L662

it can mean "we wiggled N times, and then SDA was free"
but it can also mean "we wiggled 9 times, and then did not further bother".
..which is really a different category of outcome.
We are dealing with copper traces in the outside world here, that is where real bugs live (like moth).

And since we have no return value there is a lot of responsibility here, do you really want to give up after 9 wiggle attempts? Sure, you traced it. But you might return the caller with a different state of the unverse than what he expects.

Suggestion to be verbose:
Wiggled(0..9), vs WiggledCrazy(10..31), vs WiggledDoomed

**Comment by bcantrill** [comment]
The existing trace information here seems sufficient -- if the 9 wiggles fail, the controller will likely end up being reset again.
