### ISSUE TITLE
Hubris: Host OS QSPI Driver via FPGA

### ISSUE THREAD

**Issue by nathanaelhuffman** [oxidecomputer/hubris#1790]
This is dependent on a register API for the FPGA's QSPI Flash controller which will be forthcoming.

**Comment by nathanaelhuffman** [comment]
I believe the FPGA image and maps/ in https://github.com/oxidecomputer/hubris/tree/wip-fmc are good to go wrt to starting some integration here.

Right now, the SP has exclusive access to this hardware and there's no built-in muxing to allow the SP5 access to this. That's nice for debug of the driver.  Once we've got a driver we'll get some proper muxing set up so the SP can control when the SP5 has read access to this.

**Comment by mkeeter** [comment]
Done in #1851 and subsequent PRs.
