### ISSUE TITLE
Ruby Dev Box thermal management

### ISSUE THREAD

**Issue by nathanaelhuffman** [oxidecomputer/hubris#1794]
On board chip is: https://ww1.microchip.com/downloads/aemDocuments/documents/MSLD/ProductDocuments/DataSheets/EMC2301-2-3-5-Data-Sheet-DS20006532A.pdf

Temp sensors
https://www.ti.com/lit/ds/symlink/lm75b.pdf?ts=1716228492142&ref_url=https%253A%252F%252Fwww.google.com%252F

The board we're replacing in the Ruby boxes manages the fans so unfortunately we're going to have to do *some* kind of rudimentary thermal control here to keep the ruby boxes running for sw dev.

To be clear, this is our board, *wired* into extant buses and sensors/controllers in the Ruby so we get what we were given :)

**Comment by mkeeter** [comment]
This is theoretically done but untested; see https://github.com/oxidecomputer/hubris/blob/master/task/thermal/src/bsp/grapefruit.rs
