### ISSUE TITLE
Not sure our build product caching is working super well

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#253]
I'm seeing rebuilds of a lot of crates I wouldn't expect, particularly dependencies of xtask. We should measure and investigate.

**Comment by cbiffle** [comment]
@steveklabnik you just did some work on this, should I close this issue out?

**Comment by steveklabnik** [comment]
Yes, let's consider this fixed by https://github.com/oxidecomputer/hubris/pull/180. If there's more issues popping up, I'll take another look.
