### ISSUE TITLE
"getting OpenOCD" link is broken

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [oxidecomputer/hubris#275]
On this page

https://github.com/oxidecomputer/hubris

The "getting OpenOCD" link is broken and generates a 404 error.

The link is to

http://openocd.org/getting-openocd/

But should be to

https://openocd.org/pages/getting-openocd.html

I think that the OpenOCD site/pages were reorganized recently which probably caused this mismatch.

**Comment by steveklabnik** [comment]
Thank you!

**Comment by TommyMurphyTM1234** [comment]
There another link to OpenOCD that should be going to the "getting OpenOCD" page but actually goes to the binary downloads page. Perhaps that needs to be fixed too?

https://github.com/oxidecomputer/hubris#prereqs

> If you need to build from source, you can find the OpenOCD v0.11.0 here.

**Comment by jeffallen** [comment]
@TommyMurphyTM1234 No, that part of the document is encouraging users to install version 0.11.0 from source instead of older versions, so it is correctly pointing to the source archives for precisely version 0.11.0.

**Comment by TommyMurphyTM1234** [comment]
Ah, thanks @jeffallen - I mistakenly thought that it was linking to binary builds and not source tarballs. My mistake! :-)
