### ISSUE TITLE
openssl required for Windows build

### ISSUE THREAD

**Issue by iangrunert** [oxidecomputer/hubris#298]
Looks like that step is in the github build:

https://github.com/oxidecomputer/hubris/blob/master/.github/workflows/build.yml#L70

but the README doesn't mention using vcpkg to install openssl:x64-windows which is necessary for compiling on Windows.

**Comment by labbott** [comment]
https://github.com/oxidecomputer/hubris/pull/306 merged which should also fix this issue (we no longer need openssl and therefore vcpkg)
