### ISSUE TITLE
Use -Zallow-features

### ISSUE THREAD

**Issue by bjorn3** [oxidecomputer/hubris#311]
This flag allows you to specify a list of allowed `#![feature]`s. Using any feature not part of this list will result in an error. This can be used as a roadblock to using new nightly only features which may make it easier to migrate to stable once all features that are fundamentally necessary are stabilized.

By the way it seems that several crates use `#![feature(asm)]` or `#![feature(naked_functions)]` despite not using these features.

**Comment by cbiffle** [comment]
I like it!
