### ISSUE TITLE
ITM broken on Nucleo H743/H753 boards

### ISSUE THREAD

**Issue by bcantrill** [oxidecomputer/hubris#346]
The tale of woe is in #345, but the synopsis is: ITM is (and has been) broken on the Nucleo H743/H753 boards due to TRACESWO being repurposed for SPI.  We clearly need to pick another SPI block (or at the very least, pin for SPI3_SCK) to use on this board!

**Comment by cbiffle** [comment]
I think this gets at a higher-level question, which is: permanently assigning a SPI block on the Nucleo board is weird, since we tend to use the Nucleo boards as general purpose I/O widgets. I'm not sure what to do about this.
