### ISSUE TITLE
STM32H7 SPI overruns are not handled, resulting in infinite loop

### ISSUE THREAD

**Issue by bcantrill** [oxidecomputer/hubris#349]
Currently, SPI RX overruns are not handled.  When those overruns do occur, the SPI code will take interrupts due to EOT being set, but won't actually terminate its loop -- resulting in an infinite loop.  The fix is to check for this condition (both overrun and EOT) and break out of the exchange loop, cleaning up the SPI block on the way out.

**Comment by cbiffle** [comment]
(I left some thoughts on #350.)
