### ISSUE TITLE
 java.lang.Error: Unresolved compilation problem:

### ISSUE THREAD

**Issue by PitiPipouSauvage** [oxidecomputer/hubris#355]
I just started java and i have a problem with a verry basic program .
Every time i execute it , it crashes and say " java.lang.Error: Unresolved compilation problem:"
I use Visual Code with the newest version .
And it's the first time i open a thread  so if i do things wrong i'm sorry
[test_main.txt](https://github.com/oxidecomputer/hubris/files/7799724/test_main.txt)

**Comment by PitiPipouSauvage** [comment]
`public class testMainDeux{
    public static void main(String[] args) {
        System.out.println("Hello World");
        
    }
}`

**Comment by kc8apf** [comment]
Closing as unrelated to Hubris.
