### ISSUE TITLE
Use objcopy from rust's llvm-tools-preview?

### ISSUE THREAD

**Issue by kc8apf** [oxidecomputer/hubris#449]
Rust ships llvm-tools-preview (https://github.com/rust-lang/rust/issues/85658) which includes llvm-objcopy.  This component should be installable via rust-toolchain.yaml.  Using this in xtask would remove the need for installing host system packages.

**Comment by steveklabnik** [comment]
iirc @cbiffle had said that the llvm version of these tools doesn't do the right things for some stuff we need. I don't remember more context than that.

**Comment by steveklabnik** [comment]
I did find https://github.com/oxidecomputer/hubris/commit/ac53573f9ce2df9ec86c5f2f03a9587a5e38d377

**Comment by cbiffle** [comment]
I believe we've recently ended our reliance on `objcopy` _in general_ so we can close this.
