### ISSUE TITLE
Any document (or notes) port mbed to hubris?

### ISSUE THREAD

**Issue by Shengliang** [oxidecomputer/hubris#451]
https://os.mbed.com/platforms/ supports many boards.
Any document about porting mbed family to hubris?

**Comment by kc8apf** [comment]
Hubris requires a MPU.  Many parts supported by mbed lack MPUs and thus cannot be used with Hubris.  For those that do, there isn't a straightforward porting process as Hubris and mbed have very different designs.  Hubris' kernel already has support for ARMv7-M and ARMv8-M. For M0+, M4, M7, and M33 devices that include an MPU, a small amount of initialization code will need to be written (see https://github.com/oxidecomputer/hubris/blob/master/app/lpc55xpresso/src/main.rs as an example) and then the rest is implementing device drivers for the peripherals you wish to use.
