### ISSUE TITLE
gimlet: need to enable/disable the T6 in response to power enable

### ISSUE THREAD

**Issue by rmustacc** [oxidecomputer/hubris#605]
The SP is responsible for dealing with kicking off part of the T6 power state machine. Effectively we have the signal `SP3_TO_SP_NIC_PWREN_L` (PF4) which comes out of the SP3 GPIO expander network. This signal basically indicates the intended power state of the device. When the T6 is supposed to be on this signal will be asserted and expect to remain asserted. When it goes away, it will be deasserted. When we enter A0 initially this will remain deasserted. When this is asserted and deasserted we will need to work with the Sequencer state machine to cause it to set and clear the various reset flags and/or activate the broader T6 state machine. @nathanaelhuffman can hopefully provide more on the exact sequencer SPI transactions.

**Comment by nathanaelhuffman** [comment]
new register added:
![image](https://user-images.githubusercontent.com/8078693/173961568-49411f2c-6c48-44e6-81b3-8641aa4a9bcb.png)

I can provide a patched FPGA + gimlet_regs.json upon request.

When SP pin PF4 is low, you'll need to clear the defaulted '1' in the NIC_CTRL register. When sp pin PF4 is high you'll need to set the bit in NIC_CTRL.

Do i wish this pin was wired directly to the FPGA? Yes, and maybe in the next rev :)  If long-term we want to go this direction, we could talk about using one of the spare SP->FPGA pins for this purpose but nothing avoids code unfortunately.
