### ISSUE TITLE
KSZ8463 dynamic MAC table lies about number of entries

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/hubris#669]
If you read slot 0 in the KSZ8463's MAC table when it only knows one MAC address, it will report that there is one entry (strictly, it reports that it's non-empty with "Number of Valid Entries" = 1, so there's an implied +1).

If you read slot 1, it will report that same MAC address to you again:
```
[entry 0] Ksz8463MacTable(MacTableEntry { count: 0x1, timestamp: 0x0, source: Port3, fid: 0x2, addr: [ 0xe, 0x1d, 0x15, 0x70, 0x3d, 0xbb ] })
[entry 1] Ksz8463MacTable(MacTableEntry { count: 0x1, timestamp: 0x0, source: Port3, fid: 0x2, addr: [ 0xe, 0x1d, 0x15, 0x70, 0x3d, 0xbb ] })
```

However, if you activate a _second_ devices, it will continue to report that there's only one entry in the table, even though entries 0 and 1 are both valid:

```
[entry 0] Ksz8463MacTable(MacTableEntry { count: 0x1, timestamp: 0x0, source: Port1, fid: 0x0, addr: [ 0xe, 0x1d, 0x7f, 0xc3, 0x7, 0x31 ] })
[entry 1] Ksz8463MacTable(MacTableEntry { count: 0x1, timestamp: 0x0, source: Port3, fid: 0x2, addr: [ 0xe, 0x1d, 0x15, 0x70, 0x3d, 0xbb ] })
```

**Comment by mkeeter** [comment]
Opened Microchip case #01042036

**Comment by cbiffle** [comment]
@mkeeter what work do we need to do on this?

**Comment by mkeeter** [comment]
I was holding it wrong; this works fine now.
