### ISSUE TITLE
System reset: Expose reset status register

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/hubris#700]
We should be able to ask an SP why it performed its most recent reset through `mgmt-gateway`. For the stm32h7, the relevant register is RCC_RSR (RM0433 section 8.3.39).

Implementation sketch from @cbiffle:

> * Add an IPC to Jefe similar to the existing set_state / get_state that trade in a portable form of the reset reasons, probably a 32-bit bitfield.
> * Modify the stm32xx-sys-server to read the register and send its contents to Jefe if it is non-zero, and then clear it.
> * Do the same on lpc55
> * Have mgmt-gateway read the information from Jefe.

Two additional notes:

1. It's at least theoretically possible for mgmt-gateway to ask Jefe for the state before `sys` has posted it. We can either handle this by putting the requester in a retry loop until the post happens, or by having a "I don't know the state (yet)" case at a relevant layer (e.g., the messaging between `mgmt-gateway` and MGS).
2. The API to post the state should be restricted to allow only the `sys` task as a caller.

**Comment by cbiffle** [comment]
This is superceded by #1053.
