### ISSUE TITLE
Need to add checksum support to sprockets_sp UART protocol

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/hubris#711]
The protocol currently uses hubpack for serialization with COBS for framing. We should add a checksum for each frame, since [corncobs](https://github.com/cbiffle/corncobs) doesn't provide it.

**Comment by andrewjstone** [comment]
This will build upon https://github.com/oxidecomputer/hubris/pull/611

**Comment by cbiffle** [comment]
@andrewjstone did this get done?

**Comment by andrewjstone** [comment]
> @andrewjstone did this get done?

Nope. But I don't believe any of the sp uart hacky test code got merged in anyway. That is superseded by IPCC and `host-sp-comms` which will end up calling into sprot to perform sprockets operations.

In short, this is all so out of date that we can just close it.
