### ISSUE TITLE
Add API for hubris image version information

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/hubris#813]
RFDs 108 and 181 both talk about versioning hubris images, including discussions around using an `epoch` to avoid rollback to versions we deem too old (e.g., we discover vulnerabilities). We need runtime access to this version information, and ideally would like to be able to extract the version information from an image at rest. Use cases include but are not limited to:

1. SP reports version information to MGS (for use by the update system, including the technician port during a manual update)
2. When applying updates, we'd like an SP to ensure it hasn't received the wrong kind of image (e.g., a gimlet SP receiving a sidecar SP image) before finalizing the update / rebooting
3. When applying updates and/or deciding to roll back, we need to be able to check image epochs to ensure we aren't downgrading across an epoch boundary

I think at a minimum satisfying these requires retrieving the information described in RFD 181 section 4:

```rust
struct ImageHeader {
	// Used to indicate a valid image
	magic: u32,
	// hubris version incremented on every update
	version: u32,
	// Version used to avoid rollback
	epoch: u32,
}
```

both for the current running image and from an image at rest.

**Comment by cbiffle** [comment]
I notice this is categorized as PVT1 in this repo but MVP in others -- it seems like an MVP issue to me. @smklein do you feel strongly?

**Comment by andrewjstone** [comment]
I opened https://github.com/oxidecomputer/hubris/issues/1366 to cover epochs.
