### ISSUE TITLE
Power shelf sensor support

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/hubris#873]
Once we can take inventory of the power shelves (#872), we should monitor voltage / current / fan speed / temperature (?) and log it to the `sensors` task.

**Comment by isobering** [comment]
Here's the link to Murata's application note with PMBus addresses for the EEPROM and microcontroller in each PSU:
https://www.murata.com/-/media/webrenewal/products/power/appnote/acan-114.ashx

**Comment by isobering** [comment]
Here's the list of things we'd like to monitor:
- `READ_VIN` (command code 88h, page 6)
- `READ_VOUT` (command code 8Bh, page 6)
- `READ_IIN` (command code 89h, bage 6)
- `READ_IOUT` (command code 8Ch, page 6)
- `READ_TEMPERATURE_1` (command code 8Dh, page 7)
- `READ_TEMPERATURE_2` (command code 8Eh, page 7)
- `READ_TEMPERATURE_3` (command code 8Fh, page 7)
- `READ_FAN_SPEED_1` (command code 90h, page 7)
- `READ_FAN_SPEED_2` (command code 91h, page 7)

Logging input voltage/current and output voltage/current will let us perform basic rack-level power monitoring (one of the PSC's original functional requirements). Logging PSU temperature and fan speed will let us demonstrate some basic state-of-health monitoring (another one of the PSC's original functional requirements).
