### ISSUE TITLE
Swap CSRTN pins in Renesas programming for U351 - 0x5B 0b1011 011 (Programming File Deliverable)

### ISSUE THREAD

**Issue by refugeesus** [oxidecomputer/hubris#918]
current project has CSRTN0 used for VDD_MEM_EFGH, but it's actually used for VDDCR_SOC.

Changing the MFR_REVISION to 2 and MFR_DATE to 11102022 for 11-OCT-2022.

There will be a new binary file for @bcantrill here that @ericaasen will provide. This is reflected in https://github.com/oxidecomputer/hardware-gimlet/issues/1803

**Comment by cbiffle** [comment]
@refugeesus reports that this appears to have gotten fixed.
