### ISSUE TITLE
SpRoT communications (rarely) drop a received byte on RoT side.

### ISSUE THREAD

**Issue by lzrd** [oxidecomputer/hubris#929]
It appears that the SP can send a message before the RoT has set up to receive.

See drive: Docs/Engineering/EVT2/Gimlet/SP_RoT_SPI for Salae trace in sal and csv formats.

The tell-tale is the 0xB2 code that we see clocked in by the SP. This is a code that the RoT places in its FIFOWR on CSn de-assert before it handles whatever message the SP may have delivered to it. Upon generating a response to that message, or in the case of no message received, the RoT will flush FIFOWR and prime it with zeros or its generated response to the previous message received.

This bug results in the first received byte being dropped (0x01, the protocol identifier).
The second byte is the message type. 0x01 in that position is ErrorRsp which is not a valid message from SP to RoT.
The whole message is protected by a CRC16. Invalid messages are reliably detected.
The RoT sends an ErrorRsp indicating "UnsupportedProtocol".
Adding UnsupportedProtocol as one of the retry-able error types results in recovery in all tested cases.
Therefore, this is not a critical bug. Testing shows that all cases seen so far are recoverable with one retry.

There isn't a great flow control mechanism available. The semantics of CSn and ROT_IRQ should remain simple.
The easiest thing that comes to mind is for the SP to record the SoC tick count of the previous communication and to make sure that some minimal number of ticks have passed before the next transaction.
One could just put a mandatory wait before sending any message or clocking out any response.
The code currently polls for ROT_IRQ deassertion and will flush (pulse CSn) if ROT_IRQ remains asserted.

**Comment by cbiffle** [comment]
@andrewjstone recently audited and rewrote the sprot communications stack on the RoT side and it seems to be more robust. Closing this as obsolete.
